language: rust

rust:
    - stable
    - beta
    - nightly

script:
    - cargo build --all
    - cargo test --all
    - |
        if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
        RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force cargo-tarpaulin
        RUST_BACKTRACE=1 cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash)
        echo "Uploaded code coverage"
        fi
